source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'aquaponics-controller' do
    
  use_frameworks!
  
  pod 'FontAwesome.swift', :git => 'https://github.com/thii/FontAwesome.swift.git', :branch => 'master'
  pod 'Eureka', '~> 2.0.0-beta.1'
  pod 'Alamofire'
  pod 'Locksmith'
  pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift'
  pod 'JGProgressHUD', '~> 1.4'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0'
          end
      end
  end
  
end
